### ISSUE TITLE
Inline View Not Working After Recent Update

### ISSUE THREAD

**Issue by varunsridharan** [Simonwep/pickr#132]
Hi There

After Updating Pickr With Recent Release

The Inline Option is not working

```javascript
Pickr.create({
    el: '.pcikme',
inline:true,
    theme: 'classic',});
```

```html
<div class="pcikme"></div>
```

![image](https://user-images.githubusercontent.com/1884287/62676292-fca7da00-b9c7-11e9-93ec-edd08d8963b2.png)

**Comment by Simonwep** [comment]
Thank's, fixed in #0d957f839f7c8225cd430ab2e9ca80812275c6c0 :)

**Comment by varunsridharan** [comment]
@Simonwep you again did it,man. a beast :-).  why don't you add this item in product hunt ?
like i did? 
https://www.producthunt.com/posts/urlify-2

**Comment by Simonwep** [comment]
Somebody already did this apparently: https://www.producthunt.com/posts/pickr

**Comment by varunsridharan** [comment]
@Simonwep this issue still seems to be persist. kindly check and update on this. please.

**Comment by Simonwep** [comment]
@varunsridharan It works fine, related to #136 - use `pickr.show()` to show it.

**Comment by varunsridharan** [comment]
@Simonwep i would request you to check this video please : 

https://s2.do-spaces.com/2019/Aug/22/1566493946-11.mp4

**Comment by Simonwep** [comment]
Well you haven't specialized any components which should be showed. Nothing related to the `inline` option... :/

**Comment by varunsridharan** [comment]
@Simonwep sorry i really can't understand. if you could provide me a working `inline` code it would be great and helpful.

**Comment by Simonwep** [comment]
```js
Pickr.create({
	el: 'main',
	showAlways: true,
	components: {
		palette: true,
		opacity: true,
		hue: true,
		preview: true,
		
		interaction: {
			input: true,
			save: true
		}
	}
})
```
